#pragma once

#include "test_framework.hpp"
#include "../include/aspose_jmap/JmapClient.hpp"

#include <functional>
#include <vector>
#include <string>
#include <optional>
#include <nlohmann/json.hpp>

using namespace aspose_jmap;

namespace {

/// Simple fake transport that records each request and returns a response
/// generated by a user‑supplied callback. Anonymous-namespaced: every test .cpp file
/// that links into the same test binary defines its own same-named FakeTransport with a
/// different layout - without internal linkage here, the linker treats them as one
/// ODR-violating type (undefined behavior, manifesting as random heap corruption).
class FakeTransport : public Transport {
public:
    explicit FakeTransport(std::function<HttpResponse(const HttpRequest&)> handler_)
        : handler(std::move(handler_)) {}

    HttpResponse send(const HttpRequest& request) override {
        sentRequests.push_back(request);
        return handler(request);
    }

    std::vector<HttpRequest> sentRequests;
private:
    std::function<HttpResponse(const HttpRequest&)> handler;
};

}  // namespace

/// Helper: builds a minimal Session JSON object required by Session::fromJson().
static std::string makeSessionJson() {
    nlohmann::json sess = {
        {"capabilities", nlohmann::json::object()},
        {"accounts", nlohmann::json::object()},
        {"primaryAccounts", nlohmann::json::object()},
        {"username", "user@example.test"},
        {"apiUrl", "https://example.com/api"},
        {"downloadUrl", "https://example.com/download"},
        {"uploadUrl", "https://example.com/upload"},
        {"eventSourceUrl", "https://example.com/event"},
        {"state", "state1"}
    };
    return sess.dump();
}

/// Test successful listMailboxes() call and request inspection.
AJ_TEST(MailClient_ListMailboxes_Success) {
    const std::string sessionJson = makeSessionJson();

    auto handler = [&](const HttpRequest& req) -> HttpResponse {
        if (req.method == "GET") {
            return {200, {}, sessionJson};
        } else { // POST – method call
            nlohmann::json resp = {
                {"methodResponses", {
                    {"Mailbox/get", {
                        {"list", {
                            {
                                {"id", "mb1"},
                                {"name", "Inbox"},
                                {"isSubscribed", true}
                            }
                        }}
                    }, "c1"}
                }},
                {"sessionState", "s1"}
            };
            return {200, {}, resp.dump()};
        }
    };

    auto transport = std::make_shared<FakeTransport>(handler);
    JmapClientOptions opts;
    opts.sessionUrl = "https://example.com/.well-known/jmap";
    opts.username = "user@example.test";
    opts.password = "secret";
    opts.transport = transport;

    JmapClient client(opts);
    client.connect(); // fetch session

    std::vector<Mailbox> boxes = client.listMailboxes("u1");
    AJ_ASSERT_EQ(boxes.size(), 1u);
    AJ_ASSERT_EQ(boxes[0].id.value_or(""), "mb1");
    AJ_ASSERT_EQ(boxes[0].name, "Inbox");
    AJ_ASSERT_TRUE(boxes[0].isSubscribed);

    // Verify the POST request sent to the API endpoint.
    AJ_ASSERT_EQ(transport->sentRequests.size(), 2u);
    const HttpRequest& postReq = transport->sentRequests[1];
    AJ_ASSERT_EQ(postReq.method, "POST");
    AJ_ASSERT_EQ(postReq.url, "https://example.com/api");
    AJ_ASSERT_TRUE(postReq.body.has_value());

    nlohmann::json body = nlohmann::json::parse(*postReq.body);
    AJ_ASSERT_EQ(body.at("methodCalls").size(), 1);
    const auto& inv = body.at("methodCalls")[0];
    AJ_ASSERT_EQ(inv[0].get<std::string>(), "Mailbox/get");
    AJ_ASSERT_EQ(inv[1].at("accountId").get<std::string>(), "u1");
}

/// Test getMailbox() with optional fields (null parentId, missing properties).
AJ_TEST(MailClient_GetMailbox_OptionalFields) {
    const std::string sessionJson = makeSessionJson();

    auto handler = [&](const HttpRequest& req) -> HttpResponse {
        if (req.method == "GET") {
            return {200, {}, sessionJson};
        } else {
            nlohmann::json resp = {
                {"methodResponses", {
                    {"Mailbox/get", {
                        {"list", {
                            {
                                {"id", "mb2"},
                                {"name", "Archive"},
                                {"parentId", nullptr},
                                {"isSubscribed", false}
                            }
                        }}
                    }, "c1"}
                }},
                {"sessionState", "s1"}
            };
            return {200, {}, resp.dump()};
        }
    };

    auto transport = std::make_shared<FakeTransport>(handler);
    JmapClientOptions opts;
    opts.sessionUrl = "https://example.com/.well-known/jmap";
    opts.username = "user@example.test";
    opts.password = "secret";
    opts.transport = transport;

    JmapClient client(opts);
    client.connect();

    std::vector<Mailbox> boxes = client.getMailbox("u1", std::nullopt, std::nullopt);
    AJ_ASSERT_EQ(boxes.size(), 1u);
    AJ_ASSERT_EQ(boxes[0].id.value_or(""), "mb2");
    AJ_ASSERT_EQ(boxes[0].name, "Archive");
    AJ_ASSERT_TRUE(!boxes[0].parentId.has_value());
    AJ_ASSERT_TRUE(!boxes[0].isSubscribed);
}

/// Test that a protocol error in the response propagates as an exception.
AJ_TEST(MailClient_ListMailboxes_ProtocolError) {
    const std::string sessionJson = makeSessionJson();

    auto handler = [&](const HttpRequest& req) -> HttpResponse {
        if (req.method == "GET") {
            return {200, {}, sessionJson};
        } else {
            nlohmann::json resp = {
                {"methodResponses", {
                    {"error", {
                        {"type", "unknownMethod"},
                        {"description", "Method not supported"}
                    }, "c1"}
                }}
            };
            return {200, {}, resp.dump()};
        }
    };

    auto transport = std::make_shared<FakeTransport>(handler);
    JmapClientOptions opts;
    opts.sessionUrl = "https://example.com/.well-known/jmap";
    opts.username = "user@example.test";
    opts.password = "secret";
    opts.transport = transport;

    JmapClient client(opts);
    client.connect();

    AJ_ASSERT_THROWS(client.listMailboxes("u1"), JmapProtocolError);
}

/// Test moveMessage() returns the server‑provided partial update object.
AJ_TEST(MailClient_MoveMessage_ReturnsPartial) {
    const std::string sessionJson = makeSessionJson();

    auto handler = [&](const HttpRequest& req) -> HttpResponse {
        if (req.method == "GET") {
            return {200, {}, sessionJson};
        } else {
            nlohmann::json resp = {
                {"methodResponses", {
                    {"Email/set", {
                        {"updated", {
                            {"e123", {
                                {"mailboxIds", {
                                    {"dest", true}
                                }}
                            }}
                        }}
                    }, "c1"}
                }},
                {"sessionState", "s1"}
            };
            return {200, {}, resp.dump()};
        }
    };

    auto transport = std::make_shared<FakeTransport>(handler);
    JmapClientOptions opts;
    opts.sessionUrl = "https://example.com/.well-known/jmap";
    opts.username = "user@example.test";
    opts.password = "secret";
    opts.transport = transport;

    JmapClient client(opts);
    client.connect();

    nlohmann::json upd = client.moveMessage("u1", "e123", "dest");
    AJ_ASSERT_TRUE(upd.contains("updated"));
    AJ_ASSERT_TRUE(upd.at("updated").contains("e123"));
    AJ_ASSERT_TRUE(upd.at("updated").at("e123").at("mailboxIds").at("dest").get<bool>());
}

/// Test listMessages() returns a fully-populated EmailQueryResponse.
AJ_TEST(MailClient_ListMessages_Success) {
    const std::string sessionJson = makeSessionJson();

    auto handler = [&](const HttpRequest& req) -> HttpResponse {
        if (req.method == "GET") {
            return {200, {}, sessionJson};
        } else { // POST – method call
            nlohmann::json resp = {
                {"methodResponses", {
                    {"Email/query", {
                        {"accountId", "u1"},
                        {"queryState", "qs1"},
                        {"canCalculateChanges", true},
                        {"position", 5},
                        {"ids", {"e1", "e2", "e3"}},
                        {"total", 42},
                        {"limit", 10}
                    }, "c1"}
                }},
                {"sessionState", "s1"}
            };
            return {200, {}, resp.dump()};
        }
    };

    auto transport = std::make_shared<FakeTransport>(handler);
    JmapClientOptions opts;
    opts.sessionUrl = "https://example.com/.well-known/jmap";
    opts.username = "user@example.test";
    opts.password = "secret";
    opts.transport = transport;

    JmapClient client(opts);
    client.connect(); // fetch session

    EmailQueryResponse result = client.listMessages("u1");

    AJ_ASSERT_EQ(result.accountId, "u1");
    AJ_ASSERT_EQ(result.queryState, "qs1");
    AJ_ASSERT_TRUE(result.canCalculateChanges);
    AJ_ASSERT_EQ(result.position, 5u);
    AJ_ASSERT_EQ(result.ids.size(), 3u);
    AJ_ASSERT_EQ(result.ids[0], "e1");
    AJ_ASSERT_EQ(result.ids[1], "e2");
    AJ_ASSERT_EQ(result.ids[2], "e3");
    AJ_ASSERT_TRUE(result.total.has_value());
    AJ_ASSERT_EQ(result.total.value(), 42u);
    AJ_ASSERT_TRUE(result.limit.has_value());
    AJ_ASSERT_EQ(result.limit.value(), 10u);

    // Verify the POST request sent to the API endpoint, including the default position.
    AJ_ASSERT_EQ(transport->sentRequests.size(), 2u);
    const HttpRequest& postReq = transport->sentRequests[1];
    AJ_ASSERT_EQ(postReq.method, "POST");
    AJ_ASSERT_TRUE(postReq.body.has_value());

    nlohmann::json body = nlohmann::json::parse(*postReq.body);
    const auto& inv = body.at("methodCalls")[0];
    AJ_ASSERT_EQ(inv[0].get<std::string>(), "Email/query");
    AJ_ASSERT_EQ(inv[1].at("accountId").get<std::string>(), "u1");
    AJ_ASSERT_EQ(inv[1].at("position").get<std::uint64_t>(), 0u);
    AJ_ASSERT_TRUE(inv[1].find("filter") == inv[1].end());
    AJ_ASSERT_TRUE(inv[1].find("sort") == inv[1].end());
    AJ_ASSERT_TRUE(inv[1].find("limit") == inv[1].end());
}
